# Generated by Django 5.1.3 on 2026-05-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kostenstelle (Code)')),
                ('name', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kostenstelle',
                'verbose_name_plural': 'Kostenstellen',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='SubsidyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('fixed', 'Fester Betrag (€)'), ('percent', 'Prozent vom Bruttopreis')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text="Bei 'fixed' = Euro-Betrag pro Mahlzeit. Bei 'percent' = 0..100.", max_digits=8)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=0, help_text='Höhere Zahl gewinnt.')),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to_cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_rules', to='billing.costcenter')),
            ],
            options={
                'verbose_name': 'Zuschussregel',
                'verbose_name_plural': 'Zuschussregeln',
                'ordering': ('-priority', 'name'),
            },
        ),
    ]
