# Generated by Django 5.1.3 on 2026-05-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('lunch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidyrule',
            name='applies_to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidy_rules', to='lunch.location'),
        ),
    ]
