# Generated by Django 5.1.3 on 2026-05-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntraIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=64, verbose_name='Entra Tenant-ID')),
                ('object_id', models.CharField(max_length=64, verbose_name='Entra Object-ID')),
                ('upn_at_link', models.EmailField(blank=True, max_length=254, verbose_name='UPN beim Verknüpfen')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Entra-Identität',
                'verbose_name_plural': 'Entra-Identitäten',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Mitarbeiterkennung')),
                ('must_change_password', models.BooleanField(default=False, verbose_name='Passwortänderung erforderlich')),
                ('is_active_employee', models.BooleanField(default=True, verbose_name='Aktiv (HR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benutzerprofil',
                'verbose_name_plural': 'Benutzerprofile',
            },
        ),
        migrations.CreateModel(
            name='EntraGroupMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entra_group_object_id', models.CharField(max_length=64, unique=True, verbose_name='Entra Group Object-ID')),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('django_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entra_mappings', to='auth.group')),
            ],
            options={
                'verbose_name': 'Entra-Gruppen-Mapping',
                'verbose_name_plural': 'Entra-Gruppen-Mappings',
            },
        ),
    ]
