# Generated by Django 5.1.15 on 2026-05-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_auth_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entraidentity',
            name='object_id',
            field=models.CharField(help_text='Eindeutige, unveränderliche User-ID im Tenant.', max_length=64, verbose_name='Entra Object ID (oid)'),
        ),
        migrations.AlterField(
            model_name='entraidentity',
            name='tenant_id',
            field=models.CharField(max_length=64, verbose_name='Tenant ID'),
        ),
        migrations.AlterField(
            model_name='entraidentity',
            name='upn_at_link',
            field=models.CharField(help_text='UPN/E-Mail zum Zeitpunkt der ersten Verknüpfung. Nur zu Audit-Zwecken.', max_length=254, verbose_name='UPN bei Verknüpfung'),
        ),
    ]
