# Generated by Django 5.1.3 on 2026-05-06 10:19

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Zusatzstoff',
                'verbose_name_plural': 'Zusatzstoffe',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Allergen',
                'verbose_name_plural': 'Allergene',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorien',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Standort')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kürzel')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kantine')),
                ('code', models.CharField(max_length=20, verbose_name='Kürzel')),
                ('cutoff_order_time', models.TimeField(default=datetime.time(9, 0), verbose_name='Bestellfrist (Uhrzeit am Servier-Tag)')),
                ('cancel_cutoff_minutes_before_serving', models.PositiveIntegerField(default=60, verbose_name='Storno-Frist (Minuten vor Ausgabe)')),
                ('serving_time', models.TimeField(default=datetime.time(11, 30), verbose_name='Ausgabezeit')),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canteens', to='lunch.location')),
            ],
            options={
                'verbose_name': 'Kantine',
                'verbose_name_plural': 'Kantinen',
                'ordering': ('location__name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_date', models.DateField(verbose_name='Ausgabedatum')),
                ('is_published', models.BooleanField(default=False)),
                ('canteen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealplans', to='lunch.canteen')),
            ],
            options={
                'verbose_name': 'Speiseplan',
                'verbose_name_plural': 'Speisepläne',
                'ordering': ('-serving_date', 'canteen__name'),
            },
        ),
        migrations.CreateModel(
            name='MealSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Falls leer, wird Product.price_gross verwendet.', max_digits=7, null=True)),
                ('available_qty', models.PositiveIntegerField(blank=True, help_text='Leer = unbegrenzt verfügbar.', null=True)),
                ('served_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='lunch.mealplan')),
            ],
            options={
                'verbose_name': 'Speiseplan-Position',
                'verbose_name_plural': 'Speiseplan-Positionen',
            },
        ),
        migrations.CreateModel(
            name='GuestOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_company', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_gross', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('placed', 'Bestellt'), ('cancelled', 'Storniert'), ('served', 'Ausgegeben')], default='placed', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='billing.costcenter')),
                ('host_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='accounts.userprofile')),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_orders', to='lunch.mealslot')),
            ],
            options={
                'verbose_name': 'Bewirtung',
                'verbose_name_plural': 'Bewirtungen',
                'ordering': ('-placed_at',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price_gross', models.DecimalField(decimal_places=2, max_digits=7)),
                ('subsidy_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('net_to_employee', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('placed', 'Bestellt'), ('cancelled', 'Storniert'), ('served', 'Ausgegeben')], default='placed', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_note', models.CharField(blank=True, max_length=200)),
                ('meal_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='lunch.mealslot')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Bestellung',
                'verbose_name_plural': 'Bestellungen',
                'ordering': ('-placed_at',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Bezeichnung')),
                ('description', models.TextField(blank=True)),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Bruttopreis')),
                ('kcal', models.PositiveIntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('additives', models.ManyToManyField(blank=True, to='lunch.additive')),
                ('allergens', models.ManyToManyField(blank=True, to='lunch.allergen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='lunch.category')),
            ],
            options={
                'verbose_name': 'Gericht',
                'verbose_name_plural': 'Gerichte',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mealslot',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='lunch.product'),
        ),
        migrations.AddConstraint(
            model_name='canteen',
            constraint=models.UniqueConstraint(fields=('location', 'code'), name='uniq_canteen_per_location'),
        ),
        migrations.AddConstraint(
            model_name='mealplan',
            constraint=models.UniqueConstraint(fields=('canteen', 'serving_date'), name='uniq_plan_per_canteen_date'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('user_profile', 'meal_slot'), name='uniq_order_per_user_slot'),
        ),
    ]
