# Generated by Django 5.1.3 on 2026-05-06 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_repr', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=64, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=200)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit-Eintrag',
                'verbose_name_plural': 'Audit-Log',
                'ordering': ('-at',),
                'indexes': [models.Index(fields=['action', 'at'], name='audit_audit_action_b54e72_idx')],
            },
        ),
    ]
